# Generated by Django 2.0.3 on 2018-04-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boats.OwnerProfileInfo'),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
