# Generated by Django 2.0.3 on 2018-04-20 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0002_auto_20180419_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boats.Boat')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boats.RenterProfileInfo')),
            ],
        ),
    ]
