# Generated by Django 2.0.3 on 2018-04-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0003_rentcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcontract',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
