# Generated by Django 2.0.3 on 2018-04-20 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0004_rentcontract_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatCrew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('date_take_post', models.DateField()),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boats.Boat')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('experience', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='boatcrew',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boats.Crew'),
        ),
    ]
