# Generated by Django 2.0.3 on 2018-04-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0005_auto_20180420_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='avatar',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
