# Generated by Django 2.0.3 on 2018-04-25 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0006_crew_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatcrew',
            name='boat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boats.Boat'),
        ),
        migrations.AlterField(
            model_name='ownerprofileinfo',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='renterprofileinfo',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
