# Generated by Django 2.0.3 on 2018-05-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0010_auto_20180503_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elling',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
