# Generated by Django 2.0.3 on 2018-05-03 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0011_auto_20180503_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('cause', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('days', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='repaircontract',
            name='repair_cause',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='boats.PriceList'),
        ),
    ]
