# Generated by Django 2.0.3 on 2018-05-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0012_auto_20180503_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bay',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='licence_plate',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='elling',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='elling',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
