# Generated by Django 2.0.3 on 2018-05-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0013_auto_20180506_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='privilege',
        ),
    ]
