# Generated by Django 2.0.3 on 2018-05-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0015_auto_20180509_1214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='privilege',
            new_name='privilege_m',
        ),
    ]
