# Generated by Django 2.0.3 on 2018-05-09 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0016_auto_20180509_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilege_m',
            name='id',
        ),
        migrations.AlterField(
            model_name='privilege_m',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
