# Generated by Django 2.0.3 on 2018-05-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0017_auto_20180509_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='privilege_m',
            new_name='privilege',
        ),
    ]
