# Generated by Django 2.0.3 on 2018-05-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0018_auto_20180509_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilege',
            name='user',
        ),
        migrations.DeleteModel(
            name='privilege',
        ),
    ]
