# Generated by Django 2.0.3 on 2018-05-09 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0019_auto_20180509_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='privilege_m',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role_name', models.TextField()),
            ],
            options={
                'db_table': 'privilege',
                'managed': False,
            },
        ),
    ]
